services:
  db:
    image: postgres:17
    container_name: hotel_db
    restart: always
    environment:
      - POSTGRES_USER=${LOCAL_DB_USER}
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}
      - POSTGRES_DB=${LOCAL_DB_NAME}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "${LOCAL_DB_PORT}:5432"
  backend:
    build:
      context: ./backend
    container_name: hotel-backend-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${LOCAL_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${LOCAL_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${LOCAL_DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
  frontend:
    build:
      context: ./frontend
    container_name: hotel-frontend-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
